# Generated by Django 4.1.4 on 2022-12-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221217_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='comment_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
