# Generated by Django 4.1.4 on 2022-12-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_comment_count_room_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='room',
            name='message_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='like_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
