# Generated by Django 4.1.4 on 2022-12-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_options_alter_room_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='message_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
